version: '3.8'
services:
  web_image-getter:
    image: php:8.2-apache
    container_name: breizh-ile_web-for_image-getter
    volumes:
      - ./html:/var/www/html
    ports:
      - "${WEB_PORT}:80"
    networks:
      - rezo_web_image-getter

networks:
  rezo_web_image-getter:
